"use client";

import React, { useState, useEffect } from 'react';
import { Search, Briefcase, Building2, Activity, UploadCloud } from 'lucide-react';

// Reusable mini-components defined at the top
function NavItem({ icon, text }: { icon: React.ReactNode, text: string }) {
  return (
    <div className="flex items-center px-6 py-2 text-gray-400 hover:text-white hover:bg-[#1C212D] cursor-pointer transition-colors">
      <span className="mr-3">{icon}</span>
      <span className="font-medium text-sm">{text}</span>
    </div>
  );
}

function TableRow({ symbol, price, change, vol, isPositive }: any) {
  const color = isPositive === true ? 'text-green-500' : isPositive === false ? 'text-red-500' : 'text-gray-400';
  return (
    <tr className="hover:bg-[#1C212D] transition-colors group">
      <td className="px-6 py-4 font-bold">{symbol}</td>
      <td className="px-6 py-4 text-right">{price}</td>
      <td className={`px-6 py-4 text-right ${color}`}>{change}</td>
      <td className="px-6 py-4 text-right">{vol}</td>
    </tr>
  );
}

export default function Dashboard() {
  const [marketData, setMarketData] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  // Fetch the local JSON file generated by GitHub Actions
  useEffect(() => {
    async function fetchData() {
      try {
        const response = await fetch("./market_data.json");
        const data = await response.json();
        
        const stockList = Array.isArray(data) ? data : data.reqGroupBySecurities || [];
        setMarketData(stockList);
        setIsLoading(false);
      } catch (error) {
        console.error("Error fetching data:", error);
        setIsLoading(false);
      }
    }
    fetchData();
  }, []);

  return (
    <div className="flex h-screen bg-[#0B0E14] text-white font-sans">
      
      {/* LEFT SIDEBAR */}
      <aside className="w-64 bg-[#131722] border-r border-gray-800 flex-col hidden md:flex">
        <div className="p-6">
          <h1 className="text-xl font-bold flex items-center gap-2">
            <span className="text-green-500">📈</span> Portfolio Tracker
          </h1>
        </div>

        <nav className="flex-1 overflow-y-auto">
          <div className="mb-6">
            <p className="px-6 text-xs font-semibold text-gray-500 mb-2 uppercase">Start</p>
            <NavItem icon={<Briefcase size={18} />} text="My Portfolio" />
            <div className="px-6 py-2">
               <button className="w-full flex items-center justify-center gap-2 bg-green-900/30 text-green-500 border border-green-800 rounded px-2 py-1.5 text-xs hover:bg-green-900/50 transition">
                 <UploadCloud size={14} /> Import CDS (CSV)
               </button>
            </div>
          </div>
          
          <div className="mb-6">
            <p className="px-6 text-xs font-semibold text-gray-500 mb-2 uppercase">Research</p>
            <div className="bg-[#1C212D] border-l-2 border-green-500 text-white flex items-center px-6 py-2 cursor-pointer">
              <Building2 size={18} className="mr-3 text-green-500" />
              <span className="font-medium">Market Watch</span>
            </div>
            <NavItem icon={<Activity size={18} />} text="Market Context" />
          </div>
        </nav>
      </aside>

      {/* MAIN CONTENT AREA */}
      <main className="flex-1 flex flex-col overflow-hidden">
        
        {/* TOP HEADER */}
        <header className="h-16 bg-[#131722] border-b border-gray-800 flex items-center justify-between px-6">
          <div className="flex items-center bg-[#1C212D] rounded-md px-3 py-1.5 w-64 md:w-96 border border-gray-700">
            <Search size={16} className="text-gray-400 mr-2" />
            <input 
              type="text" 
              placeholder="Search companies..." 
              className="bg-transparent border-none outline-none text-sm w-full text-gray-300"
            />
          </div>
          <div className="flex items-center gap-4 text-sm">
             <button className="text-gray-300 hover:text-white bg-gray-800 px-4 py-1.5 rounded">Sign in</button>
          </div>
        </header>

        {/* DATA TABLE */}
        <div className="p-4 md:p-8 overflow-y-auto flex-1">
          <div className="flex items-center gap-3 mb-8">
            <h2 className="text-2xl md:text-3xl font-semibold">Live Market Watch</h2>
          </div>

          <div className="bg-[#131722] rounded-lg border border-gray-800 overflow-x-auto">
            <table className="w-full text-left text-sm whitespace-nowrap">
              <thead className="bg-[#1C212D] text-gray-400 text-xs uppercase">
                <tr>
                  <th className="px-6 py-4 font-medium">Symbol</th>
                  <th className="px-6 py-4 font-medium text-right">Price (LKR)</th>
                  <th className="px-6 py-4 font-medium text-right">Chg %</th>
                  <th className="px-6 py-4 font-medium text-right">Volume</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-800">
                {isLoading ? (
                  <tr><td colSpan={4} className="px-6 py-4 text-center text-gray-500">Loading Live Data...</td></tr>
                ) : marketData.length === 0 ? (
                  <tr><td colSpan={4} className="px-6 py-4 text-center text-gray-500">No data found.</td></tr>
                ) : (
                  marketData.log ? null : marketData.map((stock: any, index: number) => {
                    const symbol = stock.symbol;
                    const price = stock.lastTradedPrice || stock.price || '0.00';
                    const change = stock.changePercentage || stock.percentageChange || '0.00';
                    const vol = stock.shareVolume || stock.tradevolume || '0';
                    const isPos = parseFloat(change) > 0 ? true : parseFloat(change) < 0 ? false : null;

                    return (
                      <TableRow 
                        key={index}
                        symbol={symbol} 
                        price={price} 
                        change={`${change}%`} 
                        vol={vol} 
                        isPositive={isPos} 
                      />
                    )
                  })
                )}
              </tbody>
            </table>
          </div>
        </div>
      </main>
    </div>
  );
}
